---
- name: Delete EC2 instance
  hosts: localhost
  gather_facts: False
  vars:
      region: ap-southeast-1
  tasks:
    - name: restart a particular instance by its ID
      amazon.aws.ec2_instance:
         name: Ansible-VM
         region: "{{ region }}"
         state: restarted
