---
- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region: ap-southeast-1
      instance_type: "{{ var_instance_type }}"
      ami: ami-02ee763250491e04a
      keypair: ansible-key # pem file name
      subnetid: subnet-0e3221d17688f263e
  
  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group: ansible # security group name
         instance_type: "{{ instance_type }}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: Ansible-VM
         instance_tags:
            Name: Ansible-VM
         vpc_subnet_id: "{{ subnetid }}"
         assign_public_ip: yes
      register: ec2
