---
- name: Comscope Add VLAN
  hosts: all
  gather_facts: no
  tasks:
    - name: Create vlan 91
      commscope.icx.icx_vlan:
        vlan_id: 91
        ip_arp_inspection: present
        purge: present
    - name: Add a single ethernet 1/1/24 as access(untagged) port to vlan 91
      commscope.icx.icx_vlan:
        name: test-vlan
        vlan_id: 91
        interfaces:
          name:
            - ethernet 1/1/24
