---
- name: Comscope Test 
  hosts: all
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable
    ansible_user: ansible
    ansible_password: 'Siloam@guest'
    ansible_become_password: 's1lo4m'
  tasks:
    - name: Add a single ethernet 1/1/48 as access(untagged) port to vlan 20
      commscope.icx.icx_vlan:
        vlan_id: 222
        ip_arp_inspection: present
        purge: true
