---
- name: Config IP
  hosts: all
  gather_facts: false
  tasks:
    - name: Run basic PowerShell script
      ansible.windows.win_powershell:
        script: |
          New-NetIPAddress -InterfaceIndex “18” -IPAddress 10.8.156.88 -PrefixLength 24 -DefaultGateway 10.8.156.1
