---
- name: Block multiple URLs on Fortigate loaded from a CSV file
  hosts: all
  ansible_connection: httpapi
  ansible_httpapi_validate_certs: 'no'
  ansible_httpapi_use_ssl: 'yes'
  ansible_httpapi_port: 65443
  ansible_network_os: fortinet.fortios.fortios
  gather_facts: no

  vars:
    vdom: "root"
    webfilter_profile_name: "webfilter"
    csv_file_path: "blocked_urls.csv"  # Path to your CSV file
  tasks:
   - name: Reading the csv file
     read_csv:
      path: "{{ csv_file_path }}"
     register: url_list
     delegate_to: localhost
   - name: display url_list data
     debug:
      var: url_list.list
   - name: Configure URL filter lists.
     fortinet.fortios.fortios_webfilter_urlfilter:
       vdom: "{{ vdom }}"
       state: "present"
       access_token: "{{ fortigate_token }}"
       webfilter_urlfilter:
         comment: "Optional comments."
         entries:
           - action: "block"
             dns_address_family: "ipv4"
             id: "{{ item.UID1 | int }}"
             referrer_host: "myhostname"
             status: "enable"
             type: "simple"
             url: "{{ item.URL }}"
             web_proxy_profile: "testing"
         id: "{{ item.UID2 | int }}"
         ip_addr_block: "enable"
         ip4_mapped_ip6: "enable"
         name: "default_name_18"
         one_arm_ips_urlfilter: "enable"
     loop: "{{ url_list.list }}" 


#    - name: Create list of urlfilter dicts with ids
##      set_fact:
 #       urlfilter_list: "{{ urlfilter_list | default([]) + [ {'id': loop.index, 'url': item, 'type': 'simple', 'action': 'block', 'status': 'enable'} ] }}"
 #     loop: "{{ blocked_urls }}"

  #  - name: Configure web filter URL filter profile with URLs from CSV
  #    fortinet.fortios.fortios_webfilter_urlfilter:
  #      access_token: "{{ fortigate_token }}"
  #      vdom: "{{ vdom }}"
  #      state: "present"
  #      webfilter_urlfilter:
   #       name: "{{ webfilter_profile_name }}"
     #     comment: "Profile to block multiple URLs from CSV"
     #     urlfilter: "{{ urlfilter_list }}"
