---
- name: Block multiple URLs on Fortigate loaded from a CSV file
  hosts: all
  gather_facts: no

  vars:
    vdom: "root"
    webfilter_profile_name: "{{ webfilter_profile_name }}"
    csv_file_path: "blocked_urls.csv"  # Path to your CSV file
  tasks:
   - name: Reading the csv file
     read_csv:
      path: "{{ csv_file_path }}"
     register: url_list
     delegate_to: localhost
   - name: display url_list data
     debug:
      var: url_list.list
   - name: Configure web filter URL filter profile with multiple blocked URLs
       fortinet.fortios.fortios_webfilter_urlfilter:
         access_token: "{{ fortigate_token }}"
         vdom: "{{ vdom }}"
         state: "present"
         webfilter_urlfilter:
           name: "{{ webfilter_profile_name }}"
           comment: "Profile to block multiple URLs"
           urlfilter:
             - id: 0
               url: "terlarang1.com"
               type: "simple"
               action: "block"
               status: "enable"

#    - name: Create list of urlfilter dicts with ids
##      set_fact:
 #       urlfilter_list: "{{ urlfilter_list | default([]) + [ {'id': loop.index, 'url': item, 'type': 'simple', 'action': 'block', 'status': 'enable'} ] }}"
 #     loop: "{{ blocked_urls }}"

  #  - name: Configure web filter URL filter profile with URLs from CSV
  #    fortinet.fortios.fortios_webfilter_urlfilter:
  #      access_token: "{{ fortigate_token }}"
  #      vdom: "{{ vdom }}"
  #      state: "present"
  #      webfilter_urlfilter:
   #       name: "{{ webfilter_profile_name }}"
     #     comment: "Profile to block multiple URLs from CSV"
     #     urlfilter: "{{ urlfilter_list }}"
