---
- name: Block multiple URLs on Fortigate loaded from a CSV file
  hosts: all
  collections:
    - fortinet.fortios
  gather_facts: no

  vars:
    vdom: "root"
    #fortigate_host:  "{{ fortigate_host }}"
    #fortigate_token: "{{ ansible_password }}"
    webfilter_profile_name: "blocked_urls_profile"
    blocked_urls_path: "blocked_urls.txt"  # Path to the text file

  tasks:
    - name: Read blocked URLs from text file into a list
      set_fact:
        blocked_urls: "{{ lookup('file', blocked_urls_path).splitlines() }}"

    - name: Create list of urlfilter dicts with ids
      set_fact:
        urlfilter_list: "{{ urlfilter_list | default([]) + [ {'id': item.0 + 1, 'url': item.1, 'type': 'simple', 'action': 'block', 'status': 'enable'} ] }}"
      loop: "{{ blocked_urls | enumerate }}"

    - name: Configure web filter URL filter profile with URLs from CSV
      fortinet.fortios.fortios_webfilter_urlfilter:
        access_token: "{{ fortigate_token }}"
        vdom: "{{ vdom }}"
        state: "present"
        webfilter_urlfilter:
          name: "{{ webfilter_profile_name }}"
          comment: "Profile to block multiple URLs from CSV"
          urlfilter: "{{ urlfilter_list }}"
