---
- name: Block multiple URLs on Fortigate loaded from a CSV file
  hosts: all
  gather_facts: no

  vars:
    vdom: "root"
    fortigate_host:  "{{ fortigate_host }}"
    fortigate_token: "{{ ansible_password }}"
    webfilter_profile_name: "webfilter"
    csv_file_path: "users.csv"  # Path to your CSV file
  tasks:
   - name: reading the csv file
     read_csv:
      path: "{{ csv_file_path }}"
     register: user_list
     delegate_to: localhost
   - name: display user_list data
     debug:
      var: user_list.list
   - name: extract Username from all dictionaries
     debug:
       msg: "{{ item.Username }}"
     loop: "{{ user_list.list }}" 
   - name: Other Username from all dictionaries
     debug:
       msg: 
         - "{{ fortigate_host }}"
         - "{{ fortigate_token }}"
   - name: Configure web filter URL filter profile with multiple blocked URLs
     fortinet.fortios.fortios_webfilter_urlfilter:
       access_token: "{{ fortigate_token }}"
       vdom: "{{ vdom }}"
       state: "present"
       webfilter_urlfilter:
         name: "{{ webfilter_profile_name }}"
         comment: "Profile to block multiple URLs"
         urlfilter:
           - id: 1
             url: "{{ item.url }}"
             type: "simple"
             action: "block"
             status: "enable"
     loop: "{{ user_list.list }}" 

#    - name: Create list of urlfilter dicts with ids
##      set_fact:
 #       urlfilter_list: "{{ urlfilter_list | default([]) + [ {'id': loop.index, 'url': item, 'type': 'simple', 'action': 'block', 'status': 'enable'} ] }}"
 #     loop: "{{ blocked_urls }}"

  #  - name: Configure web filter URL filter profile with URLs from CSV
  #    fortinet.fortios.fortios_webfilter_urlfilter:
  #      access_token: "{{ fortigate_token }}"
  #      vdom: "{{ vdom }}"
  #      state: "present"
  #      webfilter_urlfilter:
   #       name: "{{ webfilter_profile_name }}"
     #     comment: "Profile to block multiple URLs from CSV"
     #     urlfilter: "{{ urlfilter_list }}"
