- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars:
      gcp_project: vti-dev-140322
      gcp_cred_kind: serviceaccount
      zone: "asia-southeast2-a"
      region: "asia-southeast2"

  tasks:
   - name: create a address
     gcp_compute_address:
         name: 'address-instance'
         region: "{{ region }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         state: present
     register: address
   - name: create a instance
     gcp_compute_instance:
         state: present
         name: Ansible-vm
         machine_type: "e2-micro"
         disks:
           - auto_delete: true
             boot: true
             initialize_params:
               source_image: "projects/rocky-linux-cloud/global/images/rocky-linux-8-v20220126" 
         network_interfaces:
             - network: null # use default
               access_configs:
                 - name: 'External NAT'
                   nat_ip: "{{ address }}"
                   type: 'ONE_TO_ONE_NAT'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
