- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars:
      gcp_project: vti-dev-140322
      gcp_cred_kind: serviceaccount
      zone: "asia-southeast2-a"
      region: "asia-southeast2"
   - name: create a instance
     gcp_compute_instance:
         state: absent
         name: Ansible-vm
