---
- name: Backup and archive testing logs
  hosts: all
  become_method: sudo
  become_user: root
  vars:
    temp_dir: /backup/temp
    target_backup: backup
    file_pattern: testing* 
  tasks:

    - name: Create temp directory
      command: mkdir /backup/temp
    - name: Move matching log files to the temporary directory
      shell: mv /var/log/audit/{{ file_pattern }} "{{ temp_dir }}/"
    - name: Create a timestamped archive of the temporary directory
      shell: tar -czvf /{{ target_backup }}/archive_$(date +%Y%m%d_%H%M%S).tar.gz /backup/temp/
    - name: Remove the temporary directory together with its contents
      file:
        path: "{{ temp_dir }}"
        state: absent
