---
- name: Backup and archive testing logs
  hosts: all
  become: yes
  vars:
    temp_dir: /backup/temp
  tasks:

    - name: Ensure temporary directory exists
      file:
        path: "{{ temp_dir }}"
        state: directory
        mode: '0755'
    - name: Move matching log files to the temporary directory
      command: mv /var/log/audit/testing* "{{ temp_dir }}/"
    - name: Create a timestamped archive of the temporary directory
      command: tar -czvf /backup/archive_$(date +%Y%m%d_%H%M%S).tar.gz /backup/temp/
    - name: Remove the temporary directory together with its contents
      file:
        path: "{{ temp_dir }}"
        state: absent
