
- name: Harden SSH Configuration on Linux
  hosts: all
  become: yes
  vars:
    ssh_port: 2424
    sshd_config_path: /etc/ssh/sshd_config

  tasks:
    - name: Disable root login via SSH
      ansible.builtin.lineinfile:
        path: "{{ sshd_config_path }}"
        regexp: '^#?PermitRootLogin\s+'
        line: 'PermitRootLogin no'
        state: present
        backrefs: yes
        create: yes
      notify: Restart sshd

    - name: Change SSH port to {{ ssh_port }}
      ansible.builtin.lineinfile:
        path: "{{ sshd_config_path }}"
        regexp: '^#?Port\s+'
        line: "Port {{ ssh_port }}"
        state: present
        backrefs: yes
        create: yes
      notify: Restart sshd

  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
