---
- name: Install RPM Linux
  hosts: all
  gather_facts: no
  become: yes
  become_user: automation
  tasks:
    - name: Install the Apache package
      yum:
        name: httpd
        state: present
