---
- name: Deny HTTP Firewall
  gather_facts: no
  hosts: all
  tasks:
    - name: FirewallD rules
      firewalld:
        permanent: yes
        immediate: yes
        service: "{{ item }}"
        state: disabled
      with_items:
       - http
       - https
