---
- name: Replace SSL Certificate on Nginx Web Server
  hosts: all
  become: yes
  become_method: sudo
  vars:
    ssl_destination_dir: /etc/nginx/ssl
    ssl_cert_source_list_file: /secret/full.crt  # Local control machine path to text file
    ssl_key_source_list_file: /secret/ido.key
  tasks:
    - name: Backup SSL Cert
      shell: mv /etc/nginx/ssl/full.crt  /etc/nginx/ssl/full.crt.OLD
    - name: Backup SSL Key
      shell: mv /etc/nginx/ssl/ido.key  /etc/nginx/ssl/ido.key.OLD
  
    - name: Copy SSL certificate to server
      ansible.builtin.copy:
        remote_src: yes
        src: "{{ ssl_cert_source_list_file }}"
        dest: "{{ ssl_destination_dir }}/full.crt"
        owner: root
        group: root
        mode: '0644'

    - name: Copy SSL private key to server
      ansible.builtin.copy:
        remote_src: yes
        src: "{{ ssl_key_source_list_file }}"
        dest: "{{ ssl_destination_dir }}/ido.key"
        owner: root
        group: root
        mode: '0600'

    - name: Reload Nginx to apply new SSL certificate
      ansible.builtin.service:
        name: nginx
        state: reloaded
