---
- name: Install RPM Linux
  hosts: all
  gather_facts: no
  tasks:
    - name: Install the Apache package
      yum:
        name: httpd
        state: present
    - name: enable service httpd
      service:
        name: httpd
        state: started
