---
- name: CVE Vulnerability Scan and Remediation on Ubuntu
  hosts: all
  become: true
  vars:
    scan_report_path_before: /tmp/vuln_scan_report_before.html
    scan_report_path_after: /tmp/vuln_scan_report_after.html
    lynis_log_before: /tmp/lynis_scan.log
    lynis_log_after: /tmp/lynis_scan_after.log

  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install Lynis vulnerability scanner
      apt:
        name: lynis
        state: present

    - name: Re-scan vulnerabilities after remediation
      command: lynis audit system --quiet --log-file {{ lynis_log_after }}
      register: scan_result_after

    - name: Convert lynis log after remediation to HTML report
      shell: |
        echo "<html><body><pre>" > {{ scan_report_path_after }}
        cat {{ lynis_log_after }} >> {{ scan_report_path_after }}
        echo "</pre></body></html>" >> {{ scan_report_path_after }}

    - name: Fetch scan reports to control node
      fetch:
        src: "{{ item }}"
        dest: ./reports/
        flat: yes
      loop:
        - "{{ scan_report_path_after }}"
