---
- name: CVE Vulnerability Scan and Remediation on Ubuntu
  hosts: ubuntu_servers
  become: true
  vars:
    scan_report_path_before: /tmp/vuln_scan_report_before.html
    scan_report_path_after: /tmp/vuln_scan_report_after.html
    lynis_log_before: /tmp/lynis_scan.log
    lynis_log_after: /tmp/lynis_scan_after.log

  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install Lynis vulnerability scanner
      apt:
        name: lynis
        state: present

    - name: Scan vulnerabilities before remediation
      command: lynis audit system --quiet --log-file {{ lynis_log_before }}
      register: scan_result_before

    - name: Convert lynis log before remediation to HTML report
      shell: |
        echo "<html><body><pre>" > {{ scan_report_path_before }}
        cat {{ lynis_log_before }} >> {{ scan_report_path_before }}
        echo "</pre></body></html>" >> {{ scan_report_path_before }}

    - name: Extract vulnerable packages from Lynis scan log
      shell: |
        grep -Eo 'Warning|suggestion' {{ lynis_log_before }} -A 2 | grep -Eo 'pkg=.*' | sed 's/pkg=//g' | tr '\n' ' '
      register: vulnerable_pkgs_raw
      changed_when: false

    - name: Set list of vulnerable packages
      set_fact:
        vulnerable_packages: "{{ vulnerable_pkgs_raw.stdout.split() }}"
      when: vulnerable_pkgs_raw.stdout != ""

    - name: Print list of vulnerable packages detected
      debug:
        msg: "Vulnerable packages detected: {{ vulnerable_packages }}"
      when: vulnerable_packages is defined and vulnerable_packages | length > 0

    - name: Remediate vulnerabilities by upgrading vulnerable packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop: "{{ vulnerable_packages }}"
      when: vulnerable_packages is defined and vulnerable_packages | length > 0

    - name: If no specific vulnerable packages found, run full dist-upgrade as fallback
      apt:
        upgrade: dist
        update_cache: yes
      when: vulnerable_packages is not defined or vulnerable_packages | length == 0

    - name: Re-scan vulnerabilities after remediation
      command: lynis audit system --quiet --log-file {{ lynis_log_after }}
      register: scan_result_after

    - name: Convert lynis log after remediation to HTML report
      shell: |
        echo "<html><body><pre>" > {{ scan_report_path_after }}
        cat {{ lynis_log_after }} >> {{ scan_report_path_after }}
        echo "</pre></body></html>" >> {{ scan_report_path_after }}

    - name: Fetch scan reports to control node
      fetch:
        src: "{{ item }}"
        dest: ./reports/
        flat: yes
      loop:
        - "{{ scan_report_path_before }}"
        - "{{ scan_report_path_after }}"
