- name: Block multiple URLs on Fortinet via REST API
  hosts: localhost
  gather_facts: no
  vars:
    base_url: "https://10.10.40.59:65443"
    api_path: "/api/v2/cmdb/webfilter/urlfilter/1"
    csv_file_path: "urls.csv"
    api_params:
      datasource: 1
      vdom: "root"
    auth_token: "{{ fortigate_token }}"
  tasks:
    - name: Reading the csv file
      read_csv:
        path: "{{ csv_file_path }}"
      register: url_entries
      delegate_to: localhost

    - name: Build entries list with fixed parameters
      set_fact:
        entries: >-
          {{
            url_list | 
            enumerate | 
            map('community.general.dict_kv', ['url', 'id']) | 
            map('combine', {
              'action': 'block',
              'dns_address_family': 'ipv4',
              'status': 'enable',
              'type': 'simple'
            }) | list
          }}
    - name: Debug entries list
      debug:
        var: entries_list

    - name: Prepare payload with entries
      set_fact:
        payload:
          webfilter_urlfilter:
            comment: "Blocking malicious URLs via API from CSV"
            entries: "{{ entries_list }}"
    - name: Send PUT request to block multiple URLs on Fortinet
      uri:
        validate_certs: no
        url: "{{ base_url }}{{ api_path }}?datasource={{ api_params.datasource }}&vdom={{ api_params.vdom }}"
        method: POST
        headers:
          Authorization: "Bearer {{ auth_token }}"
          Content-Type: "application/json"
        body: "{{ payload | to_json }}"
        status_code: 200,204
        return_content: yes
      register: api_response

    - name: Show API response
      debug:
        var: api_response
