---
- name: Comscope Test 
  hosts: all
  gather_facts: true
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable
    ansible_user: super
    ansible_password: 'P@ssw0rd'
    ansible_become_password: 'P@ssw0rd'
  tasks:
    - name: Enable Interface
      community.network.icx_config:
        lines:
          - enable
        parents: interface ethernet 1/1/16
    - name: Config ACL
      community.network.icx_config:
        lines:
          - sequence 5 deny tcp any any eq 5985
          - sequence 10 deny tcp any any eq 5986
          - sequence 15 deny udp any any eq 5985
          - sequence 20 deny udp any any eq 5986
        parents: ip access-list extended BLOCK_SOC
    - name: Apply ACL to VLAN
      community.network.icx_config:
        lines:
          - ip access-group BLOCK_SOC out
        parents: interface ve 2
