---
- name: Comscope Test 
  hosts: all
  gather_facts: true
  connection: network_cli
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable
    ansible_user: super
    ansible_password: 'P@ssw0rd'
    ansible_become_password: 'P@ssw0rd'
  tasks:
    - name: create ipv4 acl and add rules
      commscope.icx.icx_acl_ip:
        acl_type: extended
        acl_id: 112
        extended_rules:
          - rule_type: deny
            ip_protocol_name: tcp
            source:
              host: yes
              ip_address: 1.1.1.1
            destination:
              any: yes
            precedence: routine
            state: absent
