---
- name: VMWare Object Deletion
  gather_facts: False
  vars_files:
    - vcenter_vars.yml
  hosts: localhost
  tasks:
    - name: Poweroff virtual machine name {{ vm_name1 }}
      vmware_guest_powerstate:
        name: "{{ vm_name1 }}"
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: False
        folder: "{{ folder }}"
        state: powered-off
   
    - name: Delete a virtual machine name {{ vm_name1 }}
      vmware_guest:
        name: "{{ vm_name1 }}"
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: False
        folder: "{{ folder }}"
        datacenter: "{{ datacenter }}"
        state: absent
      register: vm_result

    - name: Assert that VM {{ vm_name }} is deleted
      assert:
        that:
          - "vm_result.changed"
