---
- name: Guest Creation
  gather_facts: no
  vars_files:
    - vcenter_vars.yml
  hosts: localhost
  tasks:
    - name: Clone a virtual machine {{ vm_name1 }} from existing template {{ template_name1 }}
      vmware_guest:
        name: "{{ vm_name1 }}"
        template: "{{ template_name1 }}"
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no 
        folder: "{{ folder }}"
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster }}"
      register: vm_result

    - name: Assert that VM is created
      assert:
        that:
          - "vm_result.changed"
    - name: Poweron virtual machine name {{ vm_name1 }}
      vmware_guest_powerstate:
        name: "{{ vm_name1 }}"
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: False
        folder: "{{ folder }}"
        state: powered-on

