---
- name: Windows Directory Deny Permission
  hosts: all
  become: false
  gather_facts: false
- name: Deny Intern
  win_acl:
    path: C:\Administrator\Documents
    user: user-test
    rights: Read,Write,Modify,FullControl,Delete
    type: deny
    state: present
