---
- name: win_chocolatey module demo
  hosts: all
  become: false
  gather_facts: true
  vars:
    - packages:
      - notepadplusplus
  tasks:
    - name: install packages
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ packages }}"
        state: present
