---
- name: win_chocolatey module demo
  hosts: all
  become: false
  gather_facts: false
  vars:
    - packages:
      - notepadplusplus
  tasks:
    - name: Uninstall packages
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ packages }}"
        remove_dependencies: yes
        skip_scripts: no
        state: absent
