---
- name: Windows Directory Deny Permission
  hosts: all
  become: false
  gather_facts: true
  tasks:
    - name: Deny Intern
      win_acl:
        path: C:\Users\automation
        user: user-test
        rights: Read,Write,Modify,FullControl,Delete
        type: allow
        state: absent
