---
- name: Windows Directory Deny Permission
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Deny Intern
      win_acl:
        path: C:\Users\Administrator\Documents
        user: user-test
        rights: Read,Write,Modify,FullControl,Delete
        type: deny
        state: present
