---
- name: Scan and Remediate Folders with 'Everyone' Permissions on Windows
  hosts: all
  gather_facts: no
  vars:
    root_folder_path: "C:\\Users\\Administrator\\Documents"  # Root folder to scan

  tasks:
    - name: Gather all directories recursively under root folder
      ansible.windows.win_find:
        paths: "{{ root_folder_path }}"
        recurse: yes
        file_type: directory
      register: found_directories

    - name: Initialize list of folders with 'Everyone' permission
      ansible.builtin.set_fact:
        folders_with_everyone: []


    - name: Remove 'Everyone' permissions from folders found
      ansible.windows.win_acl:
        path:  "{{ item.path }}"
 #       path: "C:\\Users\\Administrator\\Documents\\Testing2"
        user: "Everyone"
        rights: Read,Write
        state: absent
        recurse: yes
        type: allow
      loop: "{{ found_directories.files }}"
      register: remove_permissions_result

    - name: Show result of removing 'Everyone' permissions
      debug:
        var: remove_permissions_result
