---
- name: Scan and Remediate Folders with 'Everyone' Permissions on Windows
  hosts: all
  gather_facts: no
#  become: yes
#  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    root_folder_path: "C:\\ANSIBLE"  # Root folder to scan

  tasks:
#    - name: Gather all directories recursively under root folder
##      ansible.windows.win_find:
#        paths: "{{ root_folder_path }}"
#       recurse: yes
#        file_type: directory
#      register: found_directories

#    - name: Initialize list of folders with 'Everyone' permission
#      ansible.builtin.set_fact:
#        folders_with_everyone: []


    - name: Remove 'Everyone' permissions from folders found
      ansible.windows.win_acl:
  #      path:  "{{ item.path }}"
        path: "C:\\ANSIBLE\\NEW2"
        user: "Everyone"
        rights: Read,Write,Modify,FullControl,Delete
        state: absent
        recurse: yes
        type: allow
#      loop: "{{ found_directories.files }}"
      register: remove_permissions_result

    - name: Show result of removing 'Everyone' permissions
      debug:
        var: remove_permissions_result
