---
- name: Deny HTTP on Firewall
  gather_facts: no
  hosts: all
  tasks:
    - name: Firewall rule to allow HTTP on TCP port 80
      win_firewall_rule:
        name: Remote Desktop
        localport: 80
        action: block
        direction: in
        protocol: tcp
        profiles: 
        - private
        - domain
        - public
        state: present
        enabled: yes
