---
- name: create a instance
  gce_instance:
      instance_names: "{{instance_name}}"
      zone: "{{zone}}"
      machine_type: "{{ machine_type }}"
      image: debian-8
      state: present
      disk_size: 20
