---
- name: create a instance
  gce_instance:
      instance_names: "{{instance_name}}"
      zone: "{{zone}}"
      machine_type: "{{ machine_type }}"
      service_account_email: "{{service_account_email}}"
      credentials_file: "{{ service_account_file }}"
      project_id: "{{project}}"
      image: debian-8
      state: present
      disk_size: 20
