#  cat roles/gce/tasks/instance_main.yml
---
- name: create a instance
  gce_instance:
      instance_names: "ansible-vm"
      zone: "asia-southeast2-a"
      machine_type: "e2-micro"
      image: debian-8
      state: present
      disk_size: 20
