---
- name: Listen for webhook and run ping
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Trigger ping job on payload receipt
      condition: event.payload is defined
      action:
        run_job_template:
          name: "Ping Job Template"     # must match the Job Template name in AAP/Controller
          organization: "Default"


### Excute the payload to this webhook : curl -X POST http://IPADDRESS_EDA:5000/endpoint   -H "Content-Type: application/json"   -d '{"message": "trigger ping"}'
